### PR TITLE
Update osint.md [OSINTGRAM]

### PR DESCRIPTION
**Pull request by C3n7ral051nt4g3ncy**
`Osintgram` deals only with Instagram.

### CODE REVIEW

**Comment by kain-ableton** [comment]
Me

**Comment by Infosec-House** [comment]
Good catch! Looks like I accidentally copied [One Million Tweet Map] description onto Osintigram.

**Review by Infosec-House — APPROVED** [review]
Thanks for this correction!

**Comment by C3n7ral051nt4g3ncy** [comment]
@Infosec-House My pleasure to have helped out. 👍 
Great content on your repo!

**Comment by eduardoalmeidahi** [comment]
Olá, ainda está ativo?

**Comment by Infosec-House** [comment]
> Olá, ainda está ativo?

Yes :)

**Pull request merged**
